/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BasicCheckboxInput: typeof import('./src/components/form/basicCheckboxInput.vue')['default']
    BasicForm: typeof import('./src/components/form/basicForm.vue')['default']
    BasicRadioInput: typeof import('./src/components/form/basicRadioInput.vue')['default']
    BasicSelectInput: typeof import('./src/components/form/basicSelectInput.vue')['default']
    BasicTextareaInput: typeof import('./src/components/form/basicTextareaInput.vue')['default']
    BasicTextInput: typeof import('./src/components/form/basicTextInput.vue')['default']
    copy: typeof import('./src/components/form/basicCheckboxInput copy.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestForm: typeof import('./src/components/form/testForm.vue')['default']
  }
}
